// Sidebar actions
export const SIDEBAR_OPEN = "SIDEBAR_OPEN"
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE"

// All products actions
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"

// Single products actions
export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN"
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS"
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR"

export const LOAD_PRODUCTS = "LOAD_PRODUCTS"

// View actions
export const SET_GRID_VIEW = "SET_GRID_VIEW"
export const SET_LIST_VIEW = "SET_LIST_VIEW"

// Filter actions
export const UPDATE_SORT = "UPDATE_SORT"
export const SORT_PRODUCTS = "SORT_PRODUCTS"
export const UPDATE_FILTERS = "UPDATE_FILTERS"
export const FILTER_PRODUCTS = "FILTER_PRODUCTS"
export const CLEAR_FILTERS = "CLEAR_FILTERS"

// Cart actions
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT"
export const CLEAR_CART = "CLEAR_CART"
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS"
